### ISSUE TITLE
Simple Deployment Tutorial

### ISSUE THREAD

**Issue by tjcrone** [pangeo-data/pangeo#132]
Is there a simple tutorial or video for deploying Pangeo on GCS? I'm wondering about what specific services you are using, what type of machine you are running the Jupyterhub on, etc.. I'm hoping to find something that is zero-to-pangeo, starting with what kind of computer/service to launch on GCS to host the Jupyterhub. Anything like that out there? Thanks!

**Comment by tjcrone** [comment]
I found that this: https://zero-to-jupyterhub.readthedocs.io/en/latest/ coupled with this: https://github.com/pangeo-data/pangeo/blob/master/gce/update.md probably has everything I need for what I am trying to do. Thanks!

**Comment by mrocklin** [comment]
If you had any interest in cleaning up that markdown file and putting into
documentation (with your own additions from lessons you've learned) that
would be a big help for the project.

**Comment by tjcrone** [comment]
@mrocklin, I would be happy to help with a cleaned up entry-level tutorial on deploying Pangeo. I think it would best go into the pangeo-tutorials repo. Does that work?

**Comment by mrocklin** [comment]
No strong thoughts.  I'll defer to @rabernat o this

**Comment by rabernat** [comment]
Tim, that's fantastic that you want to help with the documentation. It would be great to fill in this gap as much as possible.

Can you explain the context of what you want to do / document? You would like to spin up another pangeo deployment on GCP, independent of pangeo.pydata.org?

As for where to put it, I want all out documentation to go into this repo as part of the sphinx site:
https://github.com/pangeo-data/pangeo/tree/master/docs
This site is already deployed,
https://pangeo-data.github.io/pangeo/setup_guides/index.html
although much of the material is out of date (see e.g. #108)

**Comment by jhamman** [comment]
I finally got around to trying out the JupyterHub deployment using minikube and the helm charts in our repo. I think I got about 99%of the way there, by which I mean, kubernetes told me dask/jupyterhub were both running in active pods. But I couldn't quite figure out how to interact with the jupyterhub server.

- *Question 1*: does anyone have an established workflow for doing this? I think I need the "public url" but just couldn't find it. @mrocklin, guessing you will know the answer to this.
- *Question 2*: generally, this seems like a very nice way to develop/test these deployments. I suggest adding a section in the "simple deployment tutorial" that focuses on the use of minikube. I'd be happy to write that up once I get question 1 sorted.

**Comment by mrocklin** [comment]
Minikube is slightly different in terms of finding external IPs.  Try the following:

    minikube service list

**Comment by jgerardsimcock** [comment]
I want to setup a jupyterhub deployment that is a slight modification of the current pangeo setup.  The only difference I want to install different libraries and in the notebook and  workers. 

I've reproduced the files from the `gce` directory except the examples dir.  I've made modifications to to the docker files to install a few additional libraries. Additional edits to config files and docker files have been made to account for bucket names, logo templating and the removal of the examples dir. 

When I run the setup.sh script, I successfully create my cluster on gce but when I run
`helm install jupyterhub/jupyterhub --version=v0.6.0-9701a90 --name=jupyter --namespace=jhub-rhg -f jupyter-config.yml` 

I get this error: `Error: could not find a ready tiller pod` 

What am I missing?

**Comment by tjcrone** [comment]
@jgerardsimcock, it takes a while for the tiller pod to start up, so the script as written will fail. after the helm repo update, i added the following code to my setup.sh:

```
# wait for tiller to come up
echo "Waiting for tiller to come up ..."
test=`helm status 2>&1`
while [[ $test = *"ready tiller"* ]]; do
test=`helm status 2>&1`
sleep 1
done
echo "done."
```

This is a kluge because currently it seems that the --wait flag of helm init does not work properly. I am not requesting that my change be pulled because it is preferable that the --wait flag issue be fixed upstream. But perhaps this change to the script will help you in the mean time.

**Comment by tjcrone** [comment]
I believe my change as written may require that you change the script to a BASH script, with

```
#/bin/env bash
```

at the start of the file.

**Comment by jgerardsimcock** [comment]
Thank you @tjcrone. I've updated my setup.sh file to support waiting. I am now getting this `Error: transport is closing` I've included my juptyer-config.yml file. Is there anything obviously out of place here?

```
proxy:
  secretToken: secret

singleuser:
  image:
    name: pangeo/notebook
    tag: 2018-03-11
  #cmd: ['start-singleuser.sh']
    extraEnv:
      EXTRA_PIP_PACKAGES: >-
      GCSFUSE_BUCKET: jhub-rhg
  storage:
    extraVolumes:
      - name: fuse
        hostPath:
          path: /dev/fuse
    extraVolumeMounts:
      - name: fuse
        mountPath: /dev/fuse
  cpu:
    limit: 2
    guarantee: 1
  memory:
    limit: 4G
    guarantee: 2G

rbac:
  enabled: false

hub:
  extraConfig: |
    c.JupyterHub.log_level = 'DEBUG'
    c.KubeSpawner.singleuser_service_account = 'default'
    c.Spawner.default_url = '/lab'
    from kubernetes import client
    def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
        return pod
    c.KubeSpawner.modify_pod_hook = modify_pod_hook

  image:
    name: jupyterhub/k8s-hub
    tag: v0.6
  
cookieSecret: secret

cull:
  enabled: true
  users: false
  timeout: 3600
  every: 600
```

Also, have been documenting this and would like to know the best way to contribute to the deployment documentation. Would this be best for pangeo or is this more appropriate for the [zero-to-jupyterhub](https://zero-to-jupyterhub.readthedocs.io/en/v0.4-doc/index.html) documentation?
