### ISSUE TITLE
Using Minikube to develop pangeo kubernetes deployment

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo#137]
I have been experimenting with Minikube to debug/develop our pangeo deployment on kubernetes. My workflow looks something like this:

```
minikube start
# wait a minute while kubernetes is initialized

# follow the basic helm workflow in setup.sh
helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
helm repo update
helm install jupyterhub/jupyterhub --version=v0.6.0-9701a90 --name=jupyter --namespace=pangeo-local -f jupyter-config.yaml

# list the active services
minikube service list
```

This all seems to work so that is good. With an output that looks something like:

```
|--------------|----------------------|--------------------------------|
|  NAMESPACE   |         NAME         |              URL               |
|--------------|----------------------|--------------------------------|
| default      | kubernetes           | No node port                   |
| kube-system  | kube-dns             | No node port                   |
| kube-system  | kubernetes-dashboard | http://192.168.99.100:30000    |
| kube-system  | tiller-deploy        | No node port                   |
|              |                      | http://192.168.99.100:31828    |
| pangeo-local | hub                  | No node port                   |
| pangeo-local | proxy-api            | No node port                   |
| pangeo-local | proxy-http           | No node port                   |
| pangeo-local | proxy-public         | http://192.168.99.100:32328    |
|              |                      | http://192.168.99.100:31856    |
|--------------|----------------------|--------------------------------|
```

If I go to one of the proxy-public urls, I do in fact get JupyterHub running.

Now, I'm taking to the auth page, and then things break down. Obviously, the autho page includes a redirect to github and then back to pangeo.pydata.org.  So in the vein of me trying to learn to do this on my own, I tried swapping out a few things with the zero-to-jupyterhub minikube template (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/minikube-config.yaml) but never got a functional hub. 

So questions for either @jacobtomlinson and/or @mrocklin. 

1. do you have a custom minikube template you use for jupyterhub, presumably some combination of what is in our repo and what zero-to-jupyterhub uses)?
2. looking at my workflow described above, am I missing anything major?

**Comment by mrocklin** [comment]
If you're using the jupyter-config.yaml from this repository then you probably want to strip out all of the `auth:` section.  This will change per-cluster.

**Comment by rabernat** [comment]
cc @tjcrone

**Comment by jhamman** [comment]
okay, that got me one step further (using this config):

```yaml
proxy:
  secretToken: SECRET

singleuser:
  image:
    name: daskdev/pangeo-notebook
    tag: latest
  cmd: ['start-singleuser.sh']
  extraEnv:
    EXTRA_PIP_PACKAGES: >-
    GCSFUSE_BUCKET: pangeo-data
  storage:
    extraVolumes:
      - name: fuse
        hostPath:
          path: /dev/fuse
    extraVolumeMounts:
      - name: fuse
        mountPath: /dev/fuse
  cpu:
    limit: 2
    guarantee: 1
  memory:
    limit: 4G
    guarantee: 2G

rbac:
  enabled: false

hub:
  extraConfig: |
    c.KubeSpawner.singleuser_service_account = 'default'
    c.Spawner.default_url = '/lab'
    from kubernetes import client
    def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
        return pod
    c.KubeSpawner.modify_pod_hook = modify_pod_hook

cull:
  enabled: true
  users: false
  timeout: 1200
  every: 120
```

Now I'm stuck waiting for my server to start: 
![waiting](https://user-images.githubusercontent.com/2443309/36866144-534aaefc-1d46-11e8-95c4-5459a608e9bb.png)

I would guess this has to do with some resource constraints that I can't satisfy with my local cluster. I'm just on my laptop (8 cores, 16 GB memory). Or perhaps mounting GCS fuse. 

I would assume there is a log file somewhere that describes why this isn't working. So how do you find that?

**Comment by mrocklin** [comment]
I recommend removing the `cpu:` and `memory:` sections under `singleuser:` You could also use `kubectl get pods` to get a sense of what is running and why it's failing.  

In general when using config files you can remove *anything* and defaults will kick in.  Defaults are made to run well on minikube.

You'll also want to remove the resources in the worker-template.yaml file in your notebook pod.

**Comment by mrocklin** [comment]
Your laptop may have lots of memory, but the VM that minikube is running on may have less

**Comment by jhamman** [comment]
@mrocklin and I came up with the following `minikube` template (this is used instead of the full jupyter template in this repository): 

```yaml
proxy:
  secretToken: SECRET

singleuser:
  image:
    name: daskdev/pangeo-notebook
    tag: 2018-03-01
  cmd: ['start-singleuser.sh']
  extraEnv:
    EXTRA_PIP_PACKAGES: >-
    GCSFUSE_BUCKET: pangeo-data
  storage:
    extraVolumes:
      - name: fuse
        hostPath:
          path: /dev/fuse
    extraVolumeMounts:
      - name: fuse
        mountPath: /dev/fuse
  storage:
    type: none
  memory:
    guarantee: null

rbac:
  enabled: false

hub:
  extraConfig: |
    c.KubeSpawner.singleuser_service_account = 'default'
    c.Spawner.default_url = '/lab'
    from kubernetes import client
    def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
        return pod
    c.KubeSpawner.modify_pod_hook = modify_pod_hook

cull:
  enabled: true
  users: false
  timeout: 1200
  every: 120
```

This allow me to access the jupyterhub server and spinup user notebook pods. Before spinning up dask worker pods, I commented out the following lines from the `worker-template.yaml`:

```Yaml
    # resources:
    #   limits:
    #     cpu: "1.75"
    #     memory: 6G
    #   requests:
    #     cpu: "1.75"
    #     memory: 6G
```

*Note: I still plan to write up some additional documentation on how this went for me but I'm at the end of my workday and I didn't want to loose these key nuggets.*
