### ISSUE TITLE
worker & notebook cpu and memory settings

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo#248]
We have pangeo running on AWS and our kubernetes nodes are on  `m5.xlarge` instances, which are 4cpu, 16GB RAM. 

Our intent was to try to get 4 workers per node, so we have our `worker-template.yaml` set like this:
```
metadata:
spec:
  restartPolicy: Never
  containers:
  - args:
      - dask-worker
      - --nthreads
      - '1'
      - --no-bokeh
      - --memory-limit
      - 4GB
      - --death-timeout
      - '60'
    image: esip/pangeo-worker:2018-05-09
    name: dask-worker
    securityContext:
      capabilities:
        add: [SYS_ADMIN]
      privileged: true
    env:
      - name: GCSFUSE_BUCKET
        value: pangeo-data
    resources:
      limits:
        cpu: "900m"
        memory: 3.75G
      requests:
        cpu: "900m"
        memory: 3.75G
```
and in the `jupyterhub-config.yaml` we have:
```
  singleuser:
    image:
      name: esip/pangeo-notebook
      tag: 2018-05-09
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G
```

Does this all make sense?
