### ISSUE TITLE
Spark on Kubernetes integration

### ISSUE THREAD

**Issue by h4gen** [pangeo-data/pangeo#498]
Hey everybody,

in jupyterhub/zero-to-jupyterhub-k8s#1030 I documented how I integrated the new Spark 2.4 with PySpark support for K8s into my pangeo deployment. Maybe this is interesting for you guys?

Cheers,
Hagen

**Comment by jhamman** [comment]
If I'm remembering correctly, @mjuric and @connolly were interested in this use case.

**Comment by niallrobinson** [comment]
possibly @jacobtomlinson @dkillick @kaedonkers might want to know this exists

**Comment by abkfenris** [comment]
@greatwhiteape might this be a useful direction for your cluster?

**Comment by h4gen** [comment]
If this is interesting for you I would prepare a PR as soon as I figured out how to nicely incorporate this into the pangeo configuration. I know you guys really aim for the Pydata workflow but I think it would also be a great tool for the potential users who have an R background and who want to leverage their data on the cluster. Also the wohle interface to the apache stack is pretty intriguing to me.

**Comment by rabernat** [comment]
We would be happy to see a demo of a pangeo cluster that runs both dask and
spark.

**Comment by h4gen** [comment]
@rabernat Sure thing. Shoot me an email (address in my profile) and I show it to you!

**Comment by rabernat** [comment]
Sorry I wasn't more clear...

By "see a demo" I meant, "see a helm chart which deploys all of this stuff into one cluster."

**Comment by h4gen** [comment]
Actually there is no helm-chart yet. I use the pangeo helm chart and add the following configuration to the cluster:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: default
 name: spark-role
rules:
- apiGroups: [""]
 resources: ["pods"]
 verbs: ["get", "watch", "list", "edit", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: spark
 namespace: default
subjects:
- kind: User
 name: system:serviceaccount:pangeo:daskkubernetes
 apiGroup: ""
roleRef:
 kind: Role
 name: spark-role
 apiGroup: ""
```

Thats it. The rest is configuration of the user pod(Installing Spark as in the pyspark notebook). If you wold like to use spark via apache toree you would have to add this to the prepare script:

```
export PYSPARK_PYTHON=python3
export PYSPARK_DRIVER_PYTHON=python3
export SPARK_PUBLIC_DNS=hub.idalab.de${JUPYTERHUB_SERVICE_PREFIX}proxy/4040/jobs/
export SPARK_OPTS="--deploy-mode=client \
--master=k8s://https://kubernetes.default.svc \
--conf spark.driver.host=`hostname -I` \
--conf spark.driver.pod.name=${HOSTNAME} \
--conf spark.kubernetes.container.image=idalab/spark-py:spark \
--conf spark.ui.proxyBase=${JUPYTERHUB_SERVICE_PREFIX}proxy/4040 \
--conf spark.executor.instances=2 \
--driver-java-options=-Xms1024M \
--driver-java-options=-Xmx4096M \
--driver-java-options=-Dlog4j.logLevel=info"
```

otherwise (without toree) the user has to provide this info when the spark context is created.
Everything so far is documented [here](https://discourse.jupyter.org/t/spark-integration-documentation/243). Feel free to ask if something is unclear.
