### ISSUE TITLE
extraVolumes section in setup guide `jupyter_config.yml`

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#539]
In the setup guide, the provided `jupyter_config.yml` file has a section: 

```
    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
          revision: "b09721bb1a1248dc115730d3c8a791600eae257e"
```

But that repository doesn't seem to exist anymore. Did it move somewhere else? Does it matter?
