### ISSUE TITLE
Attaching TPUs to a GCP pangeo

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#541]
Hello everyone! Does anyone know how to attach [cloud TPUs](https://cloud.google.com/tpu/) to a Pangeo running in GCP? Is this something that came up in the ML working group (thanks for posting the video! Apologies that I haven't watched all of it yet...)?

**Comment by jhamman** [comment]
@arokem - it didn't come up, though using GPUs did. Do you want your TPUs on your Jupyter nodes or your Dask nodes?

**Comment by arokem** [comment]
Good question. I believe that I will need this on the Jupyter nodes. But
whatever works :-)

**Comment by jhamman** [comment]
In that case, I think you want to add something like the following config to the hub: https://github.com/jupyterhub/kubespawner/issues/93

```yaml
hub:
  extraConfig: |-
    c.KubeSpawner.extra_resource_limits = {"nvidia.com/gpu": "1"}
    c.KubeSpawner.extra_resource_guarantees = {"nvidia.com/gpu": "1"}
```

xref: https://github.com/jupyterhub/kubespawner/issues/93#issuecomment-423810236
