### ISSUE TITLE
Using a nifty new DNS entry, instead of an IP address

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo#542]
My neuro-themed Pangeo is up and running! This instance is going to be accessible to a relatively small group of researchers that I collaborate with directly. They are all going to be members of a GitHub org, so I would like to use GitHub OAuth for authentication. This seems to work.

Now @jhamman gave me the nifty DNS entry `learning2learn.pangeo.io` to use, but I can't quite make GitHub authentication work. There are 4 places where the IP address appears: twice in the GitHub app page, once in the jupyter_config.yaml file (under `proxy: service: leadBalancerIP`) and once in the secret_config.yaml file (under `auth: github: callbackUrl`). 

Which of these do I need to change? Do I need to change anything on the GCP side, related to the IP address? 

Thiis might also be a bit tricky to debug because my GitHub user name is under both the GitHub org that I am using for authentication, as well as explicitly entered into an `admin` block of the authentication block of the secret_config.yaml.

**Comment by jhamman** [comment]
@arokem - Does your secret yaml look something like: 

```yaml
jupyterhub:
  proxy:
    secretToken: <SECRET>

  auth:
    type: github
    github:
      clientId: "<SECRET>"
      clientSecret: <SECRET>
      callbackUrl: "http://learning2learn.pangeo.io/hub/oauth_callback"
```

**Comment by arokem** [comment]
This is what I have right now, but I've also tried with callbackURL set as
you have it:

```
jupyterhub:
proxy:
secretToken: "XXX"

# comment this out if not using github authentication
auth:
type: github
github:
clientId: "XXX"
clientSecret: "XXX"
callbackUrl: "http://123.456.789.10/hub/oauth_callback"
org_whitelist:
- "learning-2-learn"
scopes:
- "read:user"
admin:
access: true
users:
- arokem
- jhamman
```

**Comment by jhamman** [comment]
I think you need to change the callbackUrl to what I have above and make sure you've set the Github Oauth callback to points to the hub.

**Comment by arokem** [comment]
Just to make sure that I understand correctly: this means changing both of
the places in GitHub where the IP address is currently entered?

When I do that I get a "403: Forbidden"

**Comment by arokem** [comment]
<img width="1552" alt="screen shot 2019-01-30 at 10 02 39 am" src="https://user-images.githubusercontent.com/118582/52002222-47bfbe00-2476-11e9-8130-4cdf585d4fe4.png">

**Comment by jhamman** [comment]
Yes, that's right. Not sure why you are getting the forbidden response.

**Comment by arokem** [comment]
Interestingly, if I replace the URL with the IP address, the thing just
happily starts up my server and logs me in.

Should I also change the loadBalancerIP in the jupyter_config? If I try to
put `learning2learn.pangeo.io` in there I still get the 403 message, but
now I can't get in there even if I enter the IP address.

**Comment by rsignell-usgs** [comment]
In case it's useful, here's our config for pangeo.esipfed.org, where we whitelist access by github organization:
```
  auth:
    admin:
      access: true
      users:
        - jreadey
        - rsignell-usgs

    type: github
    github:
      clientId: "SECRET"
      clientSecret: "SECRET"
      callbackUrl: "http://pangeo.esipfed.org/hub/oauth_callback"
      org_whitelist:
        - "HDFGroup"
        - "pangeo-data"
        - "ESIPFed"
        - "USGS-CMG"
        - "cdi-workshops"
    scopes:
      - "read:org"
```
