### ISSUE TITLE
Possible to disable auth during testing?

### ISSUE THREAD

**Issue by samaloney** [pangeo-data/pangeo#674]
So my secret_config.yaml look like below but I still can't login any ideas?

```
# file: secret_config.yaml

jupyterhub:
  proxy:
    secretToken: "<asecret>"

  auth:
    type: dummy
    dummy:
      password: 'mypassword'
```

**Comment by tjcrone** [comment]
If you are using the [Pangeo helm chart](https://github.com/pangeo-data/helm-chart) I think you can leave everything under auth empty and it will default to the dummy authenticator. If this doesn't work for you let me know and I will help you troubleshoot.

**Comment by samaloney** [comment]
Yep I am using the scripts from [here](https://github.com/pangeo-data/pangeo/blob/master/gce/setup-guide/3_deploy_helm.sh) which I seem to use the helm chart. I get I'm getting the pangeo splash screen but it won't accept blank username/password and if I use random text kick me back to the login.

```
# file: secret_config.yaml

jupyterhub:
  proxy:
    secretToken: "<asecret>"

  auth:
```

**Comment by tjcrone** [comment]
Can you show me the portion of your hub logs related to the login? Use
```
kubectl get pods --all-namespaces
```
to get a list of pods and name spaces, then do
```
kubectl logs <HUBPODNAME> -n <NAMESPACE>
```
Do this right after you try to log in and send me the log entries that occur after you attempt to log in.

**Comment by samaloney** [comment]
No problem see below

```
kubectl logs hub-55f5c895bc-bcz67 -n pangeo
...
[I 2019-07-18 15:05:49.927 JupyterHub proxy:319] Checking routes
[I 2019-07-18 15:06:11.446 JupyterHub log:174] 200 GET /hub/login?username=test&password=tset (@10.0.1.1) 1.40ms
[I 2019-07-18 15:06:49.929 JupyterHub proxy:319] Checking routes
[I 2019-07-18 15:07:49.928 JupyterHub proxy:319] Checking routes
[I 2019-07-18 15:08:07.667 JupyterHub log:174] 200 GET /hub/login?username=ads&password=sdaf (@10.138.0.56) 1.49ms
```
Those successful 200s seem to be my login attempts which is even stranger.

**Comment by tjcrone** [comment]
Well that is confusing. It should allow you to log in. Might be a redirect problem but I'm not sure yet. Can you tell me if your notebook pod is launching? There should be a pod that includes the username you are using when you log in that will start and run. Can be seen with `kubectl get pods -n pangeo`. Logs from the proxy might tell us something as well.

**Comment by samaloney** [comment]
Yea super strange so below I've include a list of pods and logs from proxy

```
kubectl get pods -n pangeo
NAME                              READY   STATUS    RESTARTS   AGE
continuous-image-puller-htxl9     1/1     Running   0          48m
continuous-image-puller-tvnqn     1/1     Running   0          48m
continuous-image-puller-xjcsp     1/1     Running   0          48m
hub-55f5c895bc-fw27p              1/1     Running   1          48m
proxy-584cc95d8-dqr62             1/1     Running   0          48m
user-placeholder-0                1/1     Running   0          48m
user-placeholder-1                1/1     Running   0          48m
user-scheduler-66bfd86f7b-24zkr   1/1     Running   0          48m
user-scheduler-66bfd86f7b-nh6hl   1/1     Running   0          48m
```

```
 kubectl logs proxy-584cc95d8-dqr62 -n pangeo
15:21:36.478 [ConfigProxy] info: Adding route / -> http://10.4.10.182:8081
15:21:36.485 [ConfigProxy] info: Proxying http://0.0.0.0:8000 to http://10.4.10.182:8081
15:21:36.485 [ConfigProxy] info: Proxy API at http://0.0.0.0:8001/api/routes
15:21:36.488 [ConfigProxy] info: Route added / -> http://10.4.10.182:8081
15:21:59.891 [ConfigProxy] info: 200 GET /api/routes
15:21:59.895 [ConfigProxy] info: Adding route / -> http://10.4.10.182:8081
15:21:59.895 [ConfigProxy] info: Route added / -> http://10.4.10.182:8081
15:21:59.895 [ConfigProxy] info: 201 POST /api/routes/
15:22:59.900 [ConfigProxy] info: 200 GET /api/routes
15:23:59.900 [ConfigProxy] info: 200 GET /api/routes
```

**Comment by tjcrone** [comment]
Well, your user pod is not in that list. Can you try to log in again and see if a user pod tries to start?

**Comment by samaloney** [comment]
Nope I never see a change to those pods?

**Comment by tjcrone** [comment]
Okay. Can you please try logging in and then show me the Kubenetes events after a few seconds?
```
kubectl get events --all-namespaces --sort-by='{.lastTimestamp}'
```

**Comment by samaloney** [comment]
Sure doesn't look like any event happen when I try and log in

```
kubectl get events --all-namespaces --sort-by='{.lastTimestamp}'
NAMESPACE     LAST SEEN   TYPE      REASON                      KIND   MESSAGE
pangeo        48m         Warning   FailedAttachVolume          Pod    AttachVolume.Attach failed for volume "pvc-e5e7adc1-a8c7-11e9-a66f-42010a8a00e0" : error getting instance "gke-pangeo-cluster-worker-pool-b673c844-vjpr"
pangeo        47m         Normal    SuccessfulAttachVolume      Pod    AttachVolume.Attach succeeded for volume "pvc-e5e7adc1-a8c7-11e9-a66f-42010a8a00e0"
default       47m         Normal    NodeHasSufficientDisk       Node   Node gke-pangeo-cluster-worker-pool-b673c844-vjpr status is now: NodeHasSufficientDisk
default       47m         Normal    NodeHasSufficientMemory     Node   Node gke-pangeo-cluster-worker-pool-b673c844-vjpr status is now: NodeHasSufficientMemory
default       47m         Normal    NodeHasNoDiskPressure       Node   Node gke-pangeo-cluster-worker-pool-b673c844-vjpr status is now: NodeHasNoDiskPressure
default       47m         Warning   Rebooted                    Node   Node gke-pangeo-cluster-worker-pool-b673c844-vjpr has been rebooted, boot id: 513a2d82-226d-474b-b496-1da11456fb6c
default       47m         Normal    NodeNotReady                Node   Node gke-pangeo-cluster-worker-pool-b673c844-vjpr status is now: NodeNotReady
default       47m         Normal    NodeAllocatableEnforced     Node   Updated Node Allocatable limit across pods
default       47m         Normal    NodeReady                   Node   Node gke-pangeo-cluster-worker-pool-b673c844-vjpr status is now: NodeReady
default       47m         Normal    Starting                    Node   Starting kubelet.
default       47m         Normal    NodeHasSufficientPID        Node   Node gke-pangeo-cluster-worker-pool-b673c844-vjpr status is now: NodeHasSufficientPID
kube-system   47m         Normal    Pulled                      Pod    Container image "k8s.gcr.io/kube-proxy:v1.12.8-gke.10" already present on machine
pangeo        47m         Normal    Pulling                     Pod    pulling image "gcr.io/google_containers/pause:3.0"
pangeo        47m         Normal    Pulling                     Pod    pulling image "gcr.io/google_containers/pause:3.0"
kube-system   47m         Normal    Created                     Pod    Created container
pangeo        47m         Normal    Pulling                     Pod    pulling image "pangeo/base-notebook:2019.07.01"
kube-system   47m         Normal    Started                     Pod    Started container
pangeo        47m         Normal    Pulled                      Pod    Successfully pulled image "gcr.io/google_containers/pause:3.0"
pangeo        47m         Normal    Created                     Pod    Created container
pangeo        47m         Normal    Started                     Pod    Started container
default       47m         Normal    Starting                    Node   Starting kube-proxy.
kube-system   47m         Normal    Pulling                     Pod    pulling image "gcr.io/stackdriver-agents/stackdriver-logging-agent:0.6-1.6.0-1"
kube-system   47m         Normal    Pulling                     Pod    pulling image "gcr.io/kubernetes-helm/tiller:v2.14.1"
kube-system   47m         Normal    Pulled                      Pod    Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system   47m         Normal    Created                     Pod    Created container
kube-system   47m         Normal    Started                     Pod    Started container
pangeo        47m         Normal    Pulling                     Pod    pulling image "jupyterhub/k8s-hub:0.9-445a953"
pangeo        46m         Normal    Pulled                      Pod    Successfully pulled image "gcr.io/google_containers/pause:3.0"
pangeo        46m         Normal    Pulled                      Pod    Successfully pulled image "pangeo/base-notebook:2019.07.01"
kube-system   46m         Normal    Created                     Pod    Created container
kube-system   46m         Normal    Started                     Pod    Started container
pangeo        46m         Normal    Started                     Pod    Started container
kube-system   46m         Normal    Pulled                      Pod    Successfully pulled image "gcr.io/stackdriver-agents/stackdriver-logging-agent:0.6-1.6.0-1"
kube-system   46m         Normal    Created                     Pod    Created container
pangeo        46m         Normal    Created                     Pod    Created container
pangeo        46m         Normal    Started                     Pod    Started container
pangeo        46m         Normal    Created                     Pod    Created container
pangeo        46m         Normal    Pulled                      Pod    Container image "gcr.io/google_containers/pause:3.0" already present on machine
kube-system   46m         Normal    Pulled                      Pod    Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system   46m         Normal    Started                     Pod    Started container
pangeo        46m         Normal    Created                     Pod    Created container
pangeo        46m         Normal    Started                     Pod    Started container
kube-system   46m         Normal    Pulled                      Pod    Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.14.1"
kube-system   46m         Normal    Created                     Pod    Created container
kube-system   46m         Normal    Started                     Pod    Started container
pangeo        45m         Normal    Pulled                      Pod    Successfully pulled image "jupyterhub/k8s-hub:0.9-445a953"
pangeo        45m         Normal    Created                     Pod    Created container
pangeo        45m         Normal    Started                     Pod    Started container
default       42m         Normal    UnregisterNetDevice         Node   Node condition FrequentUnregisterNetDevice is now: False, reason: UnregisterNetDevice
default       42m         Normal    CorruptDockerOverlay2       Node   Node condition CorruptDockerOverlay2 is now: False, reason: CorruptDockerOverlay2
default       42m         Normal    FrequentKubeletRestart      Node   Node condition FrequentKubeletRestart is now: False, reason: FrequentKubeletRestart
default       42m         Normal    FrequentDockerRestart       Node   Node condition FrequentDockerRestart is now: False, reason: FrequentDockerRestart
default       42m         Normal    FrequentContainerdRestart   Node   Node condition FrequentContainerdRestart is now: False, reason: FrequentContainerdRestart
```

**Comment by tjcrone** [comment]
Are you sure your current context is on the cluster you think it is on? Do you have more than one cluster running?

**Comment by tjcrone** [comment]
Those entries such as CorruptDockerOverlay2 are things I have never seen before. Possibly something to look into. This issue might be beyond my level.

**Comment by tjcrone** [comment]
@jhamman or @yuvipanda any ideas?

**Comment by samaloney** [comment]
> Are you sure your current context is on the cluster you think it is on? Do you have more than one cluster running?

Yea I only have one cluster setup so I assume it it is. I just purged and redeployed same issue.

**Comment by tjcrone** [comment]
One thing I do when I am just starting out with a new deployment or new cluster is to comment out things like the Pangeo splash screen and extra volume mounts, which you don't need when getting started. I bring in new components one at a time to see if they cause problems and then solve them one at a time. Might be worth trying this approach. I wish I had more ideas at this stage, but I will keep thinking about it and reach out if I think of anything. Keep me posted if you make progress and if you have new clues.

**Comment by samaloney** [comment]
When you say comment out extra things where in the helm chart? So copy it local edit and point help to local version? Sorry I'm super new to helm, kubectl etc.

**Comment by tjcrone** [comment]
You have jupyter_config.yaml and secret_config.yaml as part of your local repo, which the scripts are using to deploy Pangeo on your cluster, and which I believe you have been editing before running scripts like https://github.com/pangeo-data/pangeo/blob/master/gce/setup-guide/3_deploy_helm.sh. Do I have this correct? Commenting things out in the jupyter_config.yaml file can be helpful for troubleshooting. Can you send your entire jupyter_config.yaml file as it is being used with this script?

**Comment by tjcrone** [comment]
Also, and you probably know this, but do not give the hub a blank username to log in, even with the dummy authenticator. It's not clear to me what it would be able to do with a blank username, since it needs to create a PVC and a pod and whatnot and it is not clear how it could really handle a blank username. I use adsf or similar when logging in with the dummy authenticator. Password does not matter unless you have used a password in your secret file. You are probably better off not using this for now, but you should definitely move toward HTTPS and GitHub authentication when you get some of these early issues hammered out.

**Comment by samaloney** [comment]
Ok sure I will try commenting out various sections and updating the deployment. Below is current config it's just taken from gce setup-guide

```
# file: jupyter_config.yaml

jupyterhub:
  singleuser:
    extraEnv:
      EXTRA_PIP_PACKAGES: >-
      GCSFUSE_BUCKET: pangeo-data
    storage:
      extraVolumes:
        - name: fuse
          hostPath:
            path: /dev/fuse
      extraVolumeMounts:
        - name: fuse
          mountPath: /dev/fuse
    cloudMetadata:
      enabled: true
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G

  hub:
    extraConfig:
      customPodHook: |
        from kubernetes import client
        def modify_pod_hook(spawner, pod):
            pod.spec.containers[0].security_context = client.V1SecurityContext(
                privileged=True,
                capabilities=client.V1Capabilities(
                    add=['SYS_ADMIN']
                )
            )
            return pod
        c.KubeSpawner.modify_pod_hook = modify_pod_hook
        c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/custom/images/logo.png'
        c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/',
                                      '/usr/local/share/jupyterhub/templates/']
    extraVolumes:
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
          revision: "b09721bb1a1248dc115730d3c8a791600eae257e"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "pangeo-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyterhub/static/custom
        name: custom-templates
        subPath: "pangeo-custom-jupyterhub-templates/assets"

  cull:
    enabled: true
    users: false
    timeout: 1200
    every: 600

  # this section specifies the IP address for pangeo
  proxy:
    service:
      loadBalancerIP: <GCE_EXTERNAL_IP>
```
