### ISSUE TITLE
memory spilling over to disk

### ISSUE THREAD

**Issue by cpatrizio88** [pangeo-data/pangeo#679]
Hello,

I am using dask-kubernetes workers to do some analysis on [ocean.pangeo.io ](https://ocean.pangeo.io) and have noticed that a large amount of data is being loaded in disk memory. I have configured my distributed.yaml file with the following, which I thought was supposed to prevent this spill over: 

```
   memory:
     target: False  # target fraction to stay below
     spill: False  # fraction at which we spill to disk
     pause: 0.80  # fraction at which we pause worker threads
```

My guess is that this is related to the issue pydata/xarray#1832 and NCAR/pop-tools#12, however I'm not exactly sure how to proceed. I am using the latest release of dask (2.1.0) and xarray (0.12.2). Any help would be greatly appreciated!

**Comment by TomAugspurger** [comment]
Let's verify that the configuration is taking. Can you connect to your KubeCluster and post the output of

```python
client = Client(cluster)
client.run(lambda dask_worker: dask_worker.memory_spill_fraction)
```

It's possible that not taking because the worker pod is started like


```yaml
     spec:
       restartPolicy: Never
       containers:
       - image: daskdev/dask:latest
         args:
           - dask-worker
           - --nthreads
           - '2'
           - --no-bokeh
           - --memory-limit
           - 6GB
           - --death-timeout
           - '60'
```

> that a large amount of data is being loaded in disk memory. 

Stepping back, I'm curious to hear a bit more about what is causing this https://github.com/pydata/xarray/issues/1832 has been improved in recent versions of dask, and I'm looking to extend that improvement to a few other places.

**Comment by cpatrizio88** [comment]
@TomAugspurger it looks like the configuration isn't taking after all:

<img width="1043" alt="Screen Shot 2019-07-29 at 9 18 29 PM" src="https://user-images.githubusercontent.com/1316945/62098342-1f5b2580-b247-11e9-9272-2f7e05034b7b.png">

My config file looks like this:

```
fuse_subgraphs: False
fuse_ave_width: 0

distributed:
  logging:
    bokeh: critical

  dashboard:
    link: /user/{JUPYTERHUB_USER}/proxy/{port}/status

  memory:
    target: False  # target fraction to stay below
    spill: False  # fraction at which we spill to disk
    pause: 0.80  # fraction at which we pause worker threads
    terminate: 0.95  # fraction at which we terminate the worker

  admin:
    tick:
      limit: 5s



kubernetes:
  count:
    max: 50
  worker-template:
    metadata:
    spec:
      nodeSelector:
        dask-worker: True
      restartPolicy: Never
      containers:
      - args:
          - dask-worker
          - --nthreads
          - '2'
          - --no-bokeh
          - --memory-limit
          - 7GB
          - --death-timeout
          - '60'
        image: ${JUPYTER_IMAGE_SPEC}
        name: dask-worker
        resources:
          limits:
            cpu: "1.75"
```

Have I specified something incorrectly? Thanks for your help!
